### ISSUE TITLE
.next Decision SpringBoot v3 support assessment

### ISSUE THREAD

**Issue by porcelli** [bamoe/bamoe-issues#19]
Provide an assess for effort and complexity to introduce support for SpringBoot v3 to Drools 8 (Kogito stream)

**Comment by baldimir** [comment]
I was able to build Spring Boot modules using Spring Boot 3.0.2 in kogito-runtimes. However the tests (and the features in general) don't work, because they need the migration to jakarta namespace as Spring Boot 3 requires Java 17. The problematic part is that the code generation is common to both Quarkus and Spring Boot. There is no separate code generation for each of the frameworks. So when code generation happens, it generates javax code, which cannot be compiled. 

I saved my changes to this branch: https://github.com/baldimir/kogito-runtimes/tree/SpringBoot3. When the jakarta move is done, I will try to rebase my changes on top of the jakarta changes. 

As this is blocked till jakarta migration is done, I am returning this to Backlog.
